### ISSUE TITLE
Support for Linux Kernel 5.15 or later (driver no longer compiles for 5.15)

### ISSUE THREAD

**Issue by bplein** [RemixVSL/iomemory-vsl#100]
The team is aware of this issue and will work on it over time. There were significant kernel changes to the block layer and this will be a fairly major fix. Please use Linux kernel 5.14 or older for now.

**Comment by bplein** [comment]
editing to reflect enhancement request status.

**Comment by snuf** [comment]
@bplein fixed, and merged on main!
