### ISSUE TITLE
[BUG] Unable to make .deb nor DKMS; error 'No such file or directory'

### ISSUE THREAD

**Issue by marcusdoc** [RemixVSL/iomemory-vsl#119]
```
git clone https://github.com/snuf/iomemory-vsl
cd iomemory-vsl
git checkout main
make dpkg
```

```
cd root/usr/src/iomemory-vsl-3.2.16 && \
               make clean
make[1]: Entering directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make \
       -j8 \
       -C /lib/modules/5.10.0-22-amd64/build \
       FIO_DRIVER_NAME=iomemory-vsl \
       FUSION_DRIVER_DIR=/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16 \
       M=/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16 \
       EXTRA_CFLAGS+="-I/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16/include -DBUIL
DING_MODULE -DLINUX_IO_SCHED -Wall -Werror" \
       KFIO_LIB=kfio/x86_64_cc102_libkfio.o_shipped \
       clean
make[2]: Entering directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make[2]: *** /lib/modules/5.10.0-22-amd64/build: No such file or directory.  Stop.
make[2]: Leaving directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make[1]: *** [Makefile:85: clean] Error 2
make[1]: Leaving directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make: *** [Makefile:35: clean] Error 2

```

Debian 11 AMD64 - fully updated

**Comment by marcusdoc** [comment]
The missing modules  for creating a .deb dpkg can be installed by
apt install dkms

**Comment by marcusdoc** [comment]
The process still though has errors.

administrator@debian:~/Desktop/iops/iomemory-vsl$ make dpkg
cd root/usr/src/iomemory-vsl-3.2.16 && \
                make clean
make[1]: Entering directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
make \
        -j8 \
        -C /lib/modules/5.10.0-22-amd64/build \
        FIO_DRIVER_NAME=iomemory-vsl \
        FUSION_DRIVER_DIR=/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16 \
        M=/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16 \
        EXTRA_CFLAGS+="-I/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16/include -DBUILDING_MODULE -DLINUX_IO_SCHED -Wall -Werror" \
        KFIO_LIB=kfio/x86_64_cc102_libkfio.o_shipped \
        clean
make[2]: Entering directory '/usr/src/linux-headers-5.10.0-22-amd64'
make[2]: Leaving directory '/usr/src/linux-headers-5.10.0-22-amd64'
rm -rf include/fio/port/linux/kfio_config.h kfio_config license.c
make[1]: Leaving directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
cd root/usr/src/iomemory-vsl-3.2.16 && \
        make patch_module_version
make[1]: Entering directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
grep: license.c: No such file or directory

Adding module version 5.10.0-22-b7bb5f0-3.2.16 to source license.c

make[1]: Leaving directory '/home/administrator/Desktop/iops/iomemory-vsl/root/usr/src/iomemory-vsl-3.2.16'
# patch fio_version, fio_short_version in debian/fio_values
cd /home/administrator/Desktop/iops/iomemory-vsl && \
        dpkg-buildpackage -rfakeroot --no-check-builddeps --no-sign
dpkg-buildpackage: info: source package iomemory-vsl
dpkg-buildpackage: info: source version 3.2.16.1732
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Support <support@fusionio.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
make[1]: Entering directory '/home/administrator/Desktop/iops/iomemory-vsl'
dh_testdir
make[1]: dh_testdir: No such file or directory
make[1]: *** [debian/rules:114: clean] Error 127
make[1]: Leaving directory '/home/administrator/Desktop/iops/iomemory-vsl'
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
make: *** [Makefile:16: dpkg] Error 2

**Comment by snuf** [comment]
The original [README](https://github.com/RemixVSL/iomemory-vsl/blob/main/README) contains the instructions and required packages.
