### ISSUE TITLE
Debian 12: Best way to mount a drive at boot time

### ISSUE THREAD

**Issue by bucovaina** [RemixVSL/iomemory-vsl#120]
Hi,

Not necessarily a bug report, but what would be the best way to mount an iodrive2 with /etc/fstab at boot time? I installed the module and "force loaded it" at boot, but then it was not mounted, if I issued the command "mount -a" it was mounted after a boot. So I added a cron entry for root with @reboot to mount the drive. 

Is there a cleaner way to achieve a mount at boot time?

**Comment by snuf** [comment]
Hi @bucovaina, I run VMs and container images from my drive, and mount it with systemd like so:
```
funs@cipher:~$ cat /etc/systemd/system/Volumes-Marvin.mount 
[Unit]
Description=Marvin FIO mount

[Mount]
What=/dev/disk/by-label/marvin
Where=/Volumes/Marvin
Type=ext4
Options=noatime,nodiratime

[Install]
WantedBy=multi-user.target
```
