### ISSUE TITLE
Debian 12 install problem

### ISSUE THREAD

**Issue by og900aero** [RemixVSL/iomemory-vsl#122]
When I run sudo dpkg-buildpackage -rfakeroot -b on Debian 12, then I get error messages:

```
make[2]: Entering directory '/usr/src/linux-headers-6.1.0-12-amd64'
/usr/src/linux-headers-6.1.0-12-common/Makefile:149: =============== ERROR ==============
/usr/src/linux-headers-6.1.0-12-common/Makefile:150: 'SUBDIRS' was removed in Linux 5.3
/usr/src/linux-headers-6.1.0-12-common/Makefile:151: Use 'M=' or 'KBUILD_EXTMOD=' instead
/usr/src/linux-headers-6.1.0-12-common/Makefile:152: ====================================
/usr/src/linux-headers-6.1.0-12-common/Makefile:153: *** ..  Stop.
make[2]: Leaving directory '/usr/src/linux-headers-6.1.0-12-amd64'
make[1]: *** [Makefile:82: modules] Error 2
make[1]: Leaving directory '/home/nio/iomemory-vsl-3.2.16.1731/driver_source'
ERROR:
make: *** [debian/rules:100: build-arch-stamp] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by snuf** [comment]
@og900aero that seems to be an issue with your headers? Have you tried `make dpkg`  from the root of the project? That seems to work on a fresh Debian 12 install:
```
dpkg-deb: building package 'iomemory-vsl-6.5.4-zabbly+' in '../iomemory-vsl-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
dpkg-deb: building package 'iomemory-vsl-initrd-6.5.4-zabbly+' in '../iomemory-vsl-initrd-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
dpkg-deb: building package 'iomemory-vsl-source' in '../iomemory-vsl-source_3.2.16.1732_amd64.deb'.
dpkg-deb: building package 'iomemory-vsl-config-6.5.4-zabbly+' in '../iomemory-vsl-config-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
dpkg-deb: building package 'iomemory-vsl-di-6.5.4-zabbly+' in 'debian/.debhelper/scratch-space/build-iomemory-vsl-di-6.5.4-zabbly+/iomemory-vsl-di-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
	Renaming iomemory-vsl-di-6.5.4-zabbly+_3.2.16.1732_amd64.deb to iomemory-vsl-di-6.5.4-zabbly+_3.2.16.1732_amd64.udeb
make[2]: Leaving directory '/home/vagrant/iomemory-vsl_dev'
make[1]: Leaving directory '/home/vagrant/iomemory-vsl_dev'
 dpkg-genbuildinfo -O../iomemory-vsl_3.2.16.1732_amd64.buildinfo
 dpkg-genchanges -O../iomemory-vsl_3.2.16.1732_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build .
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
```

**Comment by og900aero** [comment]
> @og900aero that seems to be an issue with your headers? Have you tried `make dpkg` from the root of the project? That seems to work on a fresh Debian 12 install:
> 
> ```
> dpkg-deb: building package 'iomemory-vsl-6.5.4-zabbly+' in '../iomemory-vsl-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
> dpkg-deb: building package 'iomemory-vsl-initrd-6.5.4-zabbly+' in '../iomemory-vsl-initrd-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
> dpkg-deb: building package 'iomemory-vsl-source' in '../iomemory-vsl-source_3.2.16.1732_amd64.deb'.
> dpkg-deb: building package 'iomemory-vsl-config-6.5.4-zabbly+' in '../iomemory-vsl-config-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
> dpkg-deb: building package 'iomemory-vsl-di-6.5.4-zabbly+' in 'debian/.debhelper/scratch-space/build-iomemory-vsl-di-6.5.4-zabbly+/iomemory-vsl-di-6.5.4-zabbly+_3.2.16.1732_amd64.deb'.
> 	Renaming iomemory-vsl-di-6.5.4-zabbly+_3.2.16.1732_amd64.deb to iomemory-vsl-di-6.5.4-zabbly+_3.2.16.1732_amd64.udeb
> make[2]: Leaving directory '/home/vagrant/iomemory-vsl_dev'
> make[1]: Leaving directory '/home/vagrant/iomemory-vsl_dev'
>  dpkg-genbuildinfo -O../iomemory-vsl_3.2.16.1732_amd64.buildinfo
>  dpkg-genchanges -O../iomemory-vsl_3.2.16.1732_amd64.changes
> dpkg-genchanges: info: including full source code in upload
>  dpkg-source --after-build .
> dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
> ```

I try this first, and get error message too, but I don't remember exactly to the message. I closed this session, because important this server, so I switch to the SAS SSD MIX USE 12GB MLC device.

**Comment by bplein** [comment]
Can you tell us the steps you took to get to the start of your report where you run `sudo dpkg-buildpackage -rfakeroot -b`?  It should look something like this: 
```
git clone https://github.com/RemixVSL/iomemory-vsl
cd iomemory-vsl
make dpkg
```
