### ISSUE TITLE
Can I say you are awesome?

### ISSUE THREAD

**Issue by cdoublejj** [RemixVSL/iomemory-vsl#126]
I saw that Kernel 6.6 is supported, i still have my iodrive because it's 3.4tb SSD and that's plenty. 

Thank You!

**Comment by cdoublejj** [comment]
ok i've done some reaing is this pretty stable with newer kernels? it seems newer kernels do not like some things? I'm looking to get off xubuntu to popos and was doing research and re-found this github, it's awesome it's still kicking btw,  but, i see my current linux install is kernel 5.4 vs newer kernels in popos. 6.x

**Comment by snuf** [comment]
@cdoublejj the driver goes through a test suite. If it states "tested" it means it works without losing data or any major problems/errors as far as the test-suite covers. You should be fine with any 5 or 6 kernel afaik.

**Comment by cdoublejj** [comment]
U+2764
