### ISSUE TITLE
[BUG] blk_limits_io_min missing on Linux 6.12.1

### ISSUE THREAD

**Issue by alwilson** [RemixVSL/iomemory-vsl#140]
### Bug description
Running `make module` and hitting a compile failure on arch with linux `6.12.1`

### How to reproduce
What are the steps to reproduce the reported issue.
```c
/git/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/kblock.c: In function ‘linux_bdev_expose_disk’:
/git/iomemory-vsl4/root/usr/src/iomemory-vsl4-4.3.7/kblock.c:723:5: error: implicit declaration of function ‘blk_limits_io_min’ [-Wimplicit-function-declaration]
  723 |     blk_limits_io_min(&rq->limits, bdev->bdev_block_size);
      |     ^~~~~~~~~~~~~~~~~
```

### Possible solution
Poked around https://elixir.bootlin.com and tried out just setting io_min and letting the new-ish [blk_validate_limits](https://elixir.bootlin.com/linux/v6.12.1/source/block/blk-settings.c#L226) function handle it? Although I didn't check if the driver needs to call it or if that's already done by the driver framework... I was able to load this module and mount the device.
```diff
diff --git a/root/usr/src/iomemory-vsl4-4.3.7/kblock.c b/root/usr/src/iomemory-vsl4-4.3.7/kblock.c
index b6e6138..99bb1f4 100644
--- a/root/usr/src/iomemory-vsl4-4.3.7/kblock.c
+++ b/root/usr/src/iomemory-vsl4-4.3.7/kblock.c
@@ -720,7 +720,7 @@ static int linux_bdev_expose_disk(struct fio_bdev *bdev)
       rq = disk->rq;
     }
 
-    blk_limits_io_min(&rq->limits, bdev->bdev_block_size);
+    rq->limits.io_min = bdev->bdev_block_size;
     rq->limits.io_opt = fio_dev_optimal_blk_size;
     rq->limits.max_hw_sectors = FUSION_MAX_SECTORS_PER_OS_RW_REQUEST;
     rq->limits.max_segments = bdev->bdev_max_sg_entries;
```

### Environment information
Information about the system the module is used on
1. Linux kernel compiled against (uname -a)
`Linux bigblue 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux`
2. The C compiler version used (gcc --version)
`gcc (GCC) 14.2.1 20240910`
5. distribution, and version (cat /etc/os-release)
`Arch Linux`
7. The hash. tag and/or Branch of iomemory-vsl that is being compiled (`git branch -v`)
`* main 8749a65 Update bug_report.md`
9. FIO device used, if applicable
   * fio-status
   * lspci -b -nn

**Comment by snuf** [comment]
@alwilson green, merged to main, thanks again!
